### ISSUE TITLE
ERROR SQL

### ISSUE THREAD

**Issue by JNDUFOUR** [Werkstattl/OpenBlogware#13]
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1553 Cannot drop index 'PRIMARY': needed in a foreign key constraint

**Comment by 7underlines** [comment]
Does this issue occur during an upgrade? What versions of Shopware and the plugin are currently installed?

**Comment by JNDUFOUR** [comment]
Hello, The issue occurs during the installation process, not during an upgrade. My current version of Shopware is 6.6.8.2. Thank you for your support!

**Comment by 7underlines** [comment]
Please try again with the latest plugin release, OpenBlogware 4.1.0.
I was unable to reproduce your error using the following test setup:

- Shopware 6.6.8.2
- PHP 8.3.13
- OpenBlogware 4.1.0

I tested the installation both from the backend and using bin/console commands.

Could you share the full error log from the var/log files?

**Comment by Nebukadneczar** [comment]
I also couldn't reproduce your error with the following test setup:

Shopware 6.6.9.0
PHP 8.3.14
OpenBlogware 4.1.0

It was installed via the backend, NOT via the console!
